### ISSUE TITLE
[BUG] PagerDuty multiple bugs

### ISSUE THREAD

**Issue by Kostavro** [incidentbot/incidentbot#599]
**Describe the bug**
There are a few bugs in v2.0.5 that I think are related to the upgrade from v1.

1. In `pagerduty/api.py` there's `IncidentRecord.id == channel_name` and `.where(IncidentRecord.id == channel_name)`, which fails, because `id` is not a string. I guess `channel_id` would work better in both parts of the check.

2. In `slack/messages.py` there's `if len(auto_page_targets) != 0:` but it seems like this sometimes fails with `TypeError: object of type 'NoneType' has no len()`. Would perhaps a different check avoid this error?

3. In `pagerduty/api.py` there's:
```
                        session.exec(
                            update(IncidentRecord)
                            .where(IncidentRecord.channel_id == channel_id)
                            .values(pagerduty_incidents=existing_incidents)
```
But `pagerduty_incidents` column does not exist in the v2 schema.

**Version**
v2.0.5

**To Reproduce**
1. Try to page using the PagerDuty integration.

**Expected behavior**
The PagerDuty integration pages appropriately.

**Screenshots**

**Environment (please complete the following information):**
Kubernetes, Helm Chart

**Additional context**

**Comment by echoboomer** [comment]
@Kostavro thanks for reporting this - I just pushed up `v2.0.6` which should resolve these issues. Let me know if you encounter any other problems.
