### ISSUE TITLE
[BUG] Version 2.0.6 unavailable on docker hub. 

### ISSUE THREAD

**Issue by lholland421** [incidentbot/incidentbot#601]
**Describe the bug**
Docker image version 2.0.6 unavailable on docker hub. 

**Version**
2.0.6

**To Reproduce**
Attempt to deploy the latest helm chart or the latest version of the application 2.0.6 

**Expected behavior**
Docker image is pulled and container starts 

**Environment (please complete the following information):**
 - Platform: docker, Kubernetes

**Additional context**
Unable to find the tag 2.0.6 in docker hub.

**Comment by echoboomer** [comment]
https://hub.docker.com/layers/eb129/incidentbot/v2.0.6/images/sha256-f679dba6a46af8448d02a82d6baed7f0fd99ab664c635519859bf8bf910ef990?context=explore

Can you provide any additional detail?

**Comment by lholland421** [comment]
Hey, That's odd. Its now showing on docker hub. Both 2.0.5 and 2.0.6 were not there and my nodes were unable to pull the image. Odd. 

Consider this closed :) Thanks for the help!
