### ISSUE TITLE
[FEATURE] Meeting Link not shown if incident is private

### ISSUE THREAD

**Issue by Kostavro** [incidentbot/incidentbot#610]
**Is your feature request related to a problem? Please describe.**
When a private incident channel is created, the Zoom meeting link is still posted in the digest channel, which means that anyone can join the meeting even if the incident is "private" or "security-related".

**Describe the solution you'd like**
I'd like for the digest channel message to not show the Zoom meeting link if the incident channel is created as private.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by echoboomer** [comment]
@Kostavro `v2.0.11` implements this feature. Thank for the suggestion.

**Comment by Kostavro** [comment]
Thanks @echoboomer !
