### ISSUE TITLE
[FEATURE] Statuspage update

### ISSUE THREAD

**Issue by shubhiguptaa** [incidentbot/incidentbot#612]
**Is your feature request related to a problem? Please describe.**
Yes, once the Statuspage is updated, there is no feedback on the channel if the Statuspage has an open incident. Also it will be good to control the Statuspage incident from slack, like resolve Statuspage incident when the incident is resolved.

**Describe the solution you'd like**
After an incident is open on Statuspage, there should be a message on slack channel that says Statuspage incident is opened. And either automatically resolve incident on Statuspage or a button on the slack to mark the incident on statuspage as resolved when the incident status is changed to resolved.

**Describe alternatives you've considered**

**Additional context**

**Comment by echoboomer** [comment]
@shubhiguptaa release `v2.0.11` is out now and fixes the issues with Statuspage. Many of your requests were already handled by the bot, but the process had a few bugs.

Please see the docs here for additional details: https://docs.incidentbot.io/integrations/#statuspage
