### ISSUE TITLE
[FEATURE] Publish util image with ARM

### ISSUE THREAD

**Issue by jarviliam** [incidentbot/incidentbot#617]
**Is your feature request related to a problem? Please describe.**
After a wave of recent updates to this repository, the application now starts up with a util image being run. Unfortunately it doesn't seem that this util image is built for arm

**Describe the solution you'd like**
For the util image to also be built with arm so I can run incidentbot on arm runners.

Thank you!

**Comment by echoboomer** [comment]
Hi @jarviliam, this should be resolved now as of `v2.0.14`, thanks for reporting this.
